package Classes_Terceiros;
// Generated 12/11/2015 19:54:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientePrestador generated by hbm2java
 */
public class ClientePrestador  implements java.io.Serializable {


     private Integer codclipre;
     private Servicos servicos;
     private String nome;
     private String email;
     private String tel;
     private String profissao;
     private String nomeservico;
     private String senha;
     private byte[] imagem;
     private String endereco;
     private Set agendamentos = new HashSet(0);

    public ClientePrestador() {
    }
    
	
    public ClientePrestador(String nome, String email, String tel, String senha, String endereco) {
        this.nome = nome;
        this.email = email;
        this.tel = tel;
        this.senha = senha;
        this.endereco = endereco;
    }
    public ClientePrestador(Servicos servicos, String nome, String email, String tel, String profissao, String nomeservico, String senha, byte[] imagem, String endereco, Set agendamentos) {
       this.servicos = servicos;
       this.nome = nome;
       this.email = email;
       this.tel = tel;
       this.profissao = profissao;
       this.nomeservico = nomeservico;
       this.senha = senha;
       this.imagem = imagem;
       this.endereco = endereco;
       this.agendamentos = agendamentos;
    }
   
    public Integer getCodclipre() {
        return this.codclipre;
    }
    
    public void setCodclipre(Integer codclipre) {
        this.codclipre = codclipre;
    }
    public Servicos getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Servicos servicos) {
        this.servicos = servicos;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }
    public String getNomeservico() {
        return this.nomeservico;
    }
    
    public void setNomeservico(String nomeservico) {
        this.nomeservico = nomeservico;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getAgendamentos() {
        return this.agendamentos;
    }
    
    public void setAgendamentos(Set agendamentos) {
        this.agendamentos = agendamentos;
    }




}


